"""
Setup command for bootstrapping review infrastructure.

Creates GitHub Actions workflow, Gemini styleguide, and AGENTS.md
in the target repository.
"""

import os
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


@dataclass
class ReviewSetup:
    """Current review infrastructure status."""
    codex_cli: bool = False
    gemini_cli: bool = False
    openrouter_key: bool = False
    github_actions: bool = False
    gemini_styleguide: bool = False
    agents_md: bool = False

    @property
    def cli_available(self) -> bool:
        return self.codex_cli and self.gemini_cli

    @property
    def api_available(self) -> bool:
        return self.openrouter_key

    @property
    def any_available(self) -> bool:
        return self.cli_available or self.api_available

    @property
    def fully_configured(self) -> bool:
        return self.github_actions and self.gemini_styleguide and self.agents_md

    def best_method(self) -> str:
        """Get the best available method."""
        if self.cli_available:
            return "cli"
        if self.api_available:
            return "api"
        return "unavailable"


def check_review_setup(working_dir: Path) -> ReviewSetup:
    """Check what review infrastructure exists in a repository."""
    import shutil

    setup = ReviewSetup()

    # CLI tools
    setup.codex_cli = shutil.which("codex") is not None
    setup.gemini_cli = shutil.which("gemini") is not None

    # API key
    setup.openrouter_key = bool(os.environ.get("OPENROUTER_API_KEY"))

    # Files in repo
    working_dir = Path(working_dir)
    setup.github_actions = (working_dir / ".github" / "workflows" / "ai-reviews.yml").exists()
    setup.gemini_styleguide = (working_dir / ".gemini" / "styleguide.md").exists()
    setup.agents_md = (working_dir / "AGENTS.md").exists()

    return setup


def setup_reviews(
    working_dir: Path,
    dry_run: bool = False,
    skip_actions: bool = False,
    force: bool = False,
) -> dict[str, str]:
    """
    Set up review infrastructure in a repository.

    Args:
        working_dir: Target repository directory
        dry_run: If True, don't write files, just return what would be created
        skip_actions: If True, don't create GitHub Actions workflow
        force: If True, overwrite existing files

    Returns:
        Dict of file paths to their contents (or "would create" for dry run)
    """
    working_dir = Path(working_dir).resolve()
    results = {}

    # GitHub Actions workflow
    if not skip_actions:
        actions_path = working_dir / ".github" / "workflows" / "ai-reviews.yml"
        if force or not actions_path.exists():
            results[str(actions_path)] = _write_file(
                actions_path,
                GITHUB_ACTIONS_TEMPLATE,
                dry_run
            )

    # Gemini styleguide
    styleguide_path = working_dir / ".gemini" / "styleguide.md"
    if force or not styleguide_path.exists():
        results[str(styleguide_path)] = _write_file(
            styleguide_path,
            GEMINI_STYLEGUIDE_TEMPLATE,
            dry_run
        )

    # AGENTS.md for Codex
    agents_path = working_dir / "AGENTS.md"
    if force or not agents_path.exists():
        results[str(agents_path)] = _write_file(
            agents_path,
            AGENTS_MD_TEMPLATE,
            dry_run
        )

    return results


def _write_file(path: Path, content: str, dry_run: bool) -> str:
    """Write a file or return what would be written."""
    if dry_run:
        return f"Would create: {path}"

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return f"Created: {path}"


# =============================================================================
# Templates
# =============================================================================

GITHUB_ACTIONS_TEMPLATE = """# AI Code Reviews
# Generated by workflow-orchestrator setup-reviews
# See: https://github.com/keevaspeyer10x/workflow-orchestrator

name: AI Code Reviews

on:
  pull_request:
    types: [opened, synchronize, reopened]

# Required secrets:
# - OPENAI_API_KEY: For Codex reviews
# - GEMINI_API_KEY: For Gemini reviews (if using Gemini Action directly)

jobs:
  security-review:
    name: "🔒 Security Review"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better context

      - name: Security Review (Codex)
        uses: openai/codex-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          mode: review
          custom-instructions: |
            Focus on security vulnerabilities in AI-generated code.
            Check for: injection (SQL, command, XSS), auth bypasses,
            hardcoded secrets, SSRF, path traversal, insecure deserialization.
            This code has had ZERO human review - be thorough.

  consistency-review:
    name: "🔄 Consistency Review"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Consistency Review (Gemini)
        uses: google/gemini-code-assist-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Uses .gemini/styleguide.md for custom instructions

  quality-review:
    name: "✨ Quality Review"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Quality Review (Codex)
        uses: openai/codex-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          mode: review
          custom-instructions: |
            Focus on code quality and production readiness.
            Check for: edge cases, error handling, resource cleanup,
            input validation, complexity, test coverage gaps.
            AI agents focus on happy paths - find the unhappy paths.

  holistic-review:
    name: "🎯 Holistic Review"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Holistic Review (Gemini)
        uses: google/gemini-code-assist-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          custom-prompt: |
            Review this AI-generated code with fresh eyes.
            Security, consistency, and quality reviews have already run.
            What else concerns you? Would you approve this PR?
            What questions would you ask? What would you do differently?
            Be the skeptical senior engineer this code hasn't had.
"""

GEMINI_STYLEGUIDE_TEMPLATE = """# Gemini Code Review Style Guide
# Generated by workflow-orchestrator setup-reviews

## Review Focus

This is a **vibe coding** repository where AI agents generate code
with minimal human review. Your review is a critical safety net.

## What to Look For

### 1. Codebase Consistency
- Does this code duplicate existing utilities?
- Does it follow patterns established elsewhere in this codebase?
- Are naming conventions consistent (camelCase vs snake_case)?
- Does error handling match existing patterns?

### 2. Existing Code Reuse
- Are there existing helpers/utilities that should be used?
- Is the code reinventing something that already exists?
- Could existing abstractions be leveraged?

### 3. Architecture Fit
- Does this fit the overall architecture?
- Are dependencies appropriate?
- Is the abstraction level correct?

## Output Format

When reviewing, please provide:

1. **Assessment**: APPROVED, APPROVED_WITH_NOTES, or CHANGES_REQUESTED
2. **Existing Code to Use**: List any utilities/patterns being ignored
3. **Pattern Violations**: Where it deviates from conventions
4. **Suggestions**: Non-blocking improvements

## Remember

AI coding agents solve problems in isolation. They often:
- Don't know about existing utilities
- Miss established patterns
- Create inconsistent code

**Your job is to catch what the AI missed.**
"""

AGENTS_MD_TEMPLATE = """# AGENTS.md
# Configuration for OpenAI Codex code reviews
# Generated by workflow-orchestrator setup-reviews

## Project Context

This repository uses AI-assisted development ("vibe coding").
Code is generated by AI agents with minimal human review.
Automated reviews are the primary safety net.

## Review Instructions

When reviewing code in this repository:

### Security Review Focus
- Check for injection vulnerabilities (SQL, command, XSS)
- Look for authentication/authorization bypasses
- Find hardcoded secrets or credentials
- Identify SSRF, CSRF, path traversal risks
- Verify input validation at boundaries

### Quality Review Focus
- Find edge cases that weren't handled
- Check error handling completeness
- Verify resource cleanup (files, connections)
- Look for overly complex solutions
- Identify missing test scenarios

## Project Structure

[Add your project structure here]

## Testing

[Add test commands here]
- Run tests: `npm test` or `pytest`
- Run linting: `npm run lint`

## Conventions

[Add project conventions here]
- Naming: camelCase for JS/TS, snake_case for Python
- Error handling: [describe pattern]
- Logging: [describe approach]
"""
