creation_rules:
  - path_regex: \.manus/secrets\.yaml$
    age: age14ng54a52gud0c596xp4vjxzw43hgkpus896j3tunyxejw3h3tvzq8l7jyk
  - path_regex: \.manus/secrets\.enc\.yaml$
    age: age14ng54a52gud0c596xp4vjxzw43hgkpus896j3tunyxejw3h3tvzq8l7jyk
